/**
 * Muta datele din baza locala SQLite (data/budget.db) in Postgres/Supabase.
 *
 * Rulare:
 *   node --env-file=.env.local scripts/migrate-data.mjs
 *   node --env-file=.env.local scripts/migrate-data.mjs --force   (sterge intai ce e in Postgres)
 *
 * Ruleaza intr-o singura tranzactie: ori intra tot, ori nu intra nimic.
 * Fisierul SQLite e doar citit, niciodata modificat.
 *
 * ID-urile originale sunt pastrate explicit (coloanele sunt GENERATED BY DEFAULT
 * AS IDENTITY, deci accepta valori date de noi), ca relatia dintre snapshots si
 * snapshot_balances sa ramana valida fara re-mapare. La final resetam secventele
 * ca urmatorul INSERT din aplicatie sa nu incerce sa refoloseasca un ID luat.
 */

import { DatabaseSync } from "node:sqlite";
import path from "node:path";
import fs from "node:fs";
import pg from "pg";

const force = process.argv.includes("--force");
const sqlitePath = path.join(process.cwd(), "data", "budget.db");

if (!fs.existsSync(sqlitePath)) {
  console.error(`Nu gasesc ${sqlitePath}. Rulezi din radacina proiectului?`);
  process.exit(1);
}

if (!process.env.DATABASE_URL) {
  console.error(
    "DATABASE_URL lipseste. Ruleaza cu: node --env-file=.env.local scripts/migrate-data.mjs"
  );
  process.exit(1);
}

const sqlite = new DatabaseSync(sqlitePath, { readOnly: true });

const client = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: /@(localhost|127\.0\.0\.1)/.test(process.env.DATABASE_URL)
    ? undefined
    : { rejectUnauthorized: process.env.DATABASE_SSL_NO_VERIFY !== "1" },
});

/** Tabelele in ordinea in care pot fi inserate fara sa incalce cheile straine. */
const TABLES = [
  { name: "accounts", columns: ["id", "name", "currency", "sort_order", "archived"] },
  { name: "snapshots", columns: ["id", "date", "note"] },
  {
    name: "snapshot_balances",
    columns: ["id", "snapshot_id", "account_id", "amount"],
  },
  {
    name: "recurring",
    columns: [
      "id",
      "label",
      "amount",
      "currency",
      "kind",
      "day_of_month",
      "nth_business_day",
      "active",
      "sort_order",
      "confirmed_through",
    ],
  },
  { name: "planned", columns: ["id", "label", "amount", "currency", "kind", "date", "done"] },
];

function readSqlite(table, columns) {
  return sqlite.prepare(`SELECT ${columns.join(", ")} FROM ${table} ORDER BY id`).all();
}

async function main() {
  await client.connect();

  // Verificam intai ca schema a fost aplicata.
  const { rows: existing } = await client.query(
    `SELECT table_name FROM information_schema.tables
     WHERE table_schema = 'public' AND table_name = ANY($1)`,
    [[...TABLES.map((t) => t.name), "app_settings", "trip_settings"]]
  );
  if (existing.length < TABLES.length + 2) {
    console.error(
      "Schema nu e completa in Postgres. Ruleaza intai supabase/migrations/0001_init.sql\n" +
        "(Supabase Dashboard > SQL Editor > lipesti fisierul > Run)."
    );
    process.exit(1);
  }

  // Refuzam sa suprascriem date existente fara --force.
  if (!force) {
    for (const { name } of TABLES) {
      const { rows } = await client.query(`SELECT COUNT(*)::int AS n FROM ${name}`);
      if (rows[0].n > 0) {
        console.error(
          `Tabela "${name}" are deja ${rows[0].n} randuri in Postgres.\n` +
            "Ruleaza din nou cu --force daca vrei sa le stergi si sa reimporti."
        );
        process.exit(1);
      }
    }
  }

  await client.query("BEGIN");
  try {
    if (force) {
      // Ordine inversa fata de inserare, ca sa nu lovim cheile straine.
      for (const { name } of [...TABLES].reverse()) {
        await client.query(`DELETE FROM ${name}`);
      }
    }

    let total = 0;
    for (const { name, columns } of TABLES) {
      const rows = readSqlite(name, columns);
      for (const row of rows) {
        const placeholders = columns.map((_, i) => `$${i + 1}`).join(", ");
        await client.query(
          `INSERT INTO ${name} (${columns.join(", ")}) VALUES (${placeholders})`,
          columns.map((c) => row[c] ?? null)
        );
      }
      console.log(`  ${name.padEnd(20)} ${rows.length} randuri`);
      total += rows.length;
    }

    // Randurile unice de setari: exista deja din migratie, deci le actualizam.
    const appSettings = sqlite
      .prepare("SELECT daily_budget, eur_to_ron FROM app_settings WHERE id = 1")
      .get();
    if (appSettings) {
      await client.query(
        "UPDATE app_settings SET daily_budget = $1, eur_to_ron = $2 WHERE id = 1",
        [appSettings.daily_budget, appSettings.eur_to_ron]
      );
      console.log(
        `  app_settings         buget zilnic ${appSettings.daily_budget}, curs ${appSettings.eur_to_ron}`
      );
    }

    const tripSettings = sqlite
      .prepare("SELECT trip_date, trip_cost, trip_name FROM trip_settings WHERE id = 1")
      .get();
    if (tripSettings) {
      await client.query(
        "UPDATE trip_settings SET trip_date = $1, trip_cost = $2, trip_name = $3 WHERE id = 1",
        [tripSettings.trip_date ?? null, tripSettings.trip_cost ?? null, tripSettings.trip_name ?? null]
      );
      console.log(`  trip_settings        ${tripSettings.trip_date ?? "(fara data)"}`);
    }

    // Am inserat ID-uri explicit, deci secventele au ramas in urma. Fara asta,
    // primul INSERT facut din aplicatie ar incerca id = 1 si ar da conflict.
    for (const { name } of TABLES) {
      await client.query(
        `SELECT setval(
           pg_get_serial_sequence($1, 'id'),
           COALESCE((SELECT MAX(id) FROM ${name}), 0) + 1,
           false
         )`,
        [name]
      );
    }

    await client.query("COMMIT");
    console.log(`\nGata: ${total} randuri mutate in Postgres.`);
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("\nMigrarea a esuat, nimic nu a fost scris:");
    throw error;
  } finally {
    await client.end();
    sqlite.close();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
