-- Schema initiala, portata din lib/db.ts (SQLite) in Postgres.
--
-- Doua decizii deliberate, ca sa nu se schimbe nimic in types.ts si in UI:
--
-- 1. Flag-urile raman INTEGER 0/1, nu boolean. Tipurile din lib/types.ts le
--    declara `number` (archived, active, done, received), iar paginile compara
--    direct cu 0/1. Un boolean ar fi mai curat in Postgres, dar ar cere
--    modificari in tot UI-ul pentru zero castig functional.
--
-- 2. Coloanele de data (snapshots.date, planned.date, recurring.confirmed_through)
--    raman TEXT in format YYYY-MM-DD, nu tipul `date`. Toata logica din
--    lib/balance.ts, lib/verdict.ts si lib/dates.ts lucreaza pe string-uri ISO;
--    tipul `date` ar face driverul sa intoarca obiecte Date si ar rupe
--    comparatiile de forma `a.date <= b.date`.
--
-- Tabelele vechi (months, entries, checkins, checkin_settings) nu sunt portate:
-- nu mai sunt referite nicaieri in cod, iar datele lor au fost mutate deja in
-- modelul nou de migrateFromMonthsIfNeeded().

-- accounts: conturile userului (BT, cash RON, cash EUR...). Soldul lor NU se
-- tine aici, ci in snapshot_balances -- accounts e doar definitia (nume, valuta).
CREATE TABLE IF NOT EXISTS accounts (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  currency    text NOT NULL DEFAULT 'RON' CHECK (currency IN ('RON', 'EUR')),
  sort_order  integer NOT NULL DEFAULT 0,
  archived    integer NOT NULL DEFAULT 0
);

-- snapshots: o "notare" a averii la o data (o singura data per zi).
CREATE TABLE IF NOT EXISTS snapshots (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date        text NOT NULL UNIQUE,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- soldul fiecarui cont la un anumit snapshot, in valuta contului.
CREATE TABLE IF NOT EXISTS snapshot_balances (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id  integer NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
  account_id   integer NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  amount       double precision NOT NULL DEFAULT 0,
  UNIQUE (snapshot_id, account_id)
);

-- recurring: plati/venituri lunare recurente, globale (nu sunt legate de o luna).
-- day_of_month si nth_business_day sunt exclusive: fie ziua fixa din luna, fie
-- a N-a zi lucratoare (ex: salariu platit in a 4-a zi lucratoare).
CREATE TABLE IF NOT EXISTS recurring (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label             text NOT NULL,
  amount            double precision NOT NULL DEFAULT 0,
  currency          text NOT NULL DEFAULT 'RON' CHECK (currency IN ('RON', 'EUR')),
  kind              text NOT NULL CHECK (kind IN ('income', 'expense')),
  day_of_month      integer,
  nth_business_day  integer,
  active            integer NOT NULL DEFAULT 1,
  sort_order        integer NOT NULL DEFAULT 0,
  -- data (YYYY-MM-DD) pana la care userul a confirmat ca ocurentele chiar au
  -- avut loc; cele <= aceasta data nu mai apar ca "urmeaza" in /plati.
  confirmed_through text
);

-- planned: plati/venituri unice, cu data exacta (ex: o factura, un bonus).
CREATE TABLE IF NOT EXISTS planned (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label     text NOT NULL,
  amount    double precision NOT NULL DEFAULT 0,
  currency  text NOT NULL DEFAULT 'RON' CHECK (currency IN ('RON', 'EUR')),
  kind      text NOT NULL CHECK (kind IN ('income', 'expense')),
  date      text NOT NULL,
  done      integer NOT NULL DEFAULT 0
);

-- app_settings / trip_settings: randuri unice (id = 1).
CREATE TABLE IF NOT EXISTS app_settings (
  id            integer PRIMARY KEY CHECK (id = 1),
  daily_budget  double precision NOT NULL DEFAULT 70,
  eur_to_ron    double precision NOT NULL DEFAULT 5.0
);

CREATE TABLE IF NOT EXISTS trip_settings (
  id         integer PRIMARY KEY CHECK (id = 1),
  trip_date  text,
  trip_cost  double precision,
  trip_name  text
);

INSERT INTO app_settings (id, daily_budget, eur_to_ron)
VALUES (1, 70, 5.0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO trip_settings (id, trip_date, trip_cost, trip_name)
VALUES (1, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_snapshot_balances_snapshot
  ON snapshot_balances (snapshot_id);

-- ---------------------------------------------------------------------------
-- Securitate
-- ---------------------------------------------------------------------------
-- Autentificarea aplicatiei e Clerk, iar accesul la baza se face exclusiv
-- server-side, printr-o conexiune Postgres directa cu utilizatorul `postgres`
-- (care oricum ignora RLS). Rolurile `anon` si `authenticated` -- adica cine
-- ajunge prin Data API-ul public al Supabase, cu cheia publishable -- nu au ce
-- cauta aici.
--
-- Activam RLS FARA nicio policy: fara policy, RLS respinge tot. Plus revocam
-- explicit grant-urile, ca tabelele sa nu fie expuse nici daca Data API-ul e
-- pornit din dashboard. Cele doua impreuna inseamna ca un URL public cu cheia
-- anon nu poate citi nimic.
ALTER TABLE accounts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE snapshots         ENABLE ROW LEVEL SECURITY;
ALTER TABLE snapshot_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE recurring         ENABLE ROW LEVEL SECURITY;
ALTER TABLE planned           ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings      ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_settings     ENABLE ROW LEVEL SECURITY;

-- Rolurile `anon` si `authenticated` exista doar pe Supabase. Pe un Postgres
-- obisnuit (ex: container local de test) REVOKE ar da eroare si ar opri
-- migratia, asa ca revocam doar rolurile care chiar exista.
DO $$
DECLARE
  r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format(
        'REVOKE ALL ON accounts, snapshots, snapshot_balances, recurring, ' ||
        'planned, app_settings, trip_settings FROM %I', r
      );
    END IF;
  END LOOP;
END
$$;
