-- goals: obiective de economisire multiple, cu CRUD din UI. Inlocuieste
-- trip_settings (randul unic id=1) ca model pentru pagina de proiectie.
-- trip_settings ramane in schema neatinsa, ca plasa de siguranta / istoric --
-- nu mai e scrisa de aplicatie dupa aceasta migratie.
CREATE TABLE IF NOT EXISTS goals (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  target_date    text,
  target_amount  double precision,
  sort_order     integer NOT NULL DEFAULT 0,
  archived       integer NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_goals_archived ON goals (archived);

-- migrare unica: daca exista un trip_settings vechi cu trip_date si inca nu
-- exista niciun goal, il aducem ca prim obiectiv (idempotenta: nu ruleaza a
-- doua oara odata ce exista macar un rand in goals).
INSERT INTO goals (name, target_date, target_amount, sort_order)
SELECT COALESCE(NULLIF(trip_name, ''), 'Călătorie'), trip_date, trip_cost, 0
FROM trip_settings
WHERE id = 1
  AND trip_date IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM goals);

ALTER TABLE goals ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON goals FROM %I', r);
    END IF;
  END LOOP;
END
$$;
